export const FETCH_LATEST_RELEASE_MOVIES = 'FETCH_LATEST_RELEASE_MOVIES'
export const FETCH_SINGLE_MOVIE = 'FETCH_SINGLE_MOVIE'
export const FETCH_MOVIE_RECOMMENDATIONS = 'FETCH_MOVIE_RECOMMENDATIONS'
export const ADD_MOVIE_RATING = 'ADD_MOVIE_RATING'
